### ISSUE TITLE
Normalize axes across years

### ISSUE THREAD

**Issue by PatMyron** [mevdschee/aoc-stats#1]
https://twitter.com/jeroenheijmans/status/1077232386029617153

**Comment by mevdschee** [comment]
Yeah, but making them equal is not the same as normalizing. If you want to use them to read the difficulty you need to compensate for the number of players. Given a lognormal(?) distribution of the player responses (could be determined if we had more data) then we could try to normalize them using that data. I guess you just want to give them the same axis right?

**Comment by PatMyron** [comment]
I was thinking about making them equal. Accounting for the number of players would be interesting too but would require more work

**Comment by mevdschee** [comment]
I feel the puzzles are getting harder every year, especially this year. Showing them on the same axis gives the impression these numbers are somehow comparable, while they aren't. If we would know what time it took the majority of them players (the mode or the highest frequency in histogram with 5 minute buckets?) to solve the puzzle then those times would be comparable. Anyway I don't think changing the axis is a good move unless you see a way to weigh in the (total) player count.

**Comment by PatMyron** [comment]
Was still curious about the simpler comparison for 2019/2020, so I made this:
![aoc](https://user-images.githubusercontent.com/7014355/144731763-7da63374-17c0-453b-933e-fde0e8d0fe88.png)

Also, number of stars seems to be published here now:
https://adventofcode.com/stats

**Comment by mevdschee** [comment]
>Was still curious about the simpler comparison for 2019/2020, so I made this:

It is a nice picture, but IMHO not very clear to show the difficulty per year, maybe show a line graph with the 100th answer per part per year, with years on the x axis and time on the y axis to show a comparison, with different colored lines per day, ill give it a try later.

>Also, number of stars seems to be published here now:

Yes they are, but they keep accumulating, so they are a bad indicator of the number of people that were trying to reach the leader board.

**Comment by mevdschee** [comment]
Relevant twitter thread: https://twitter.com/mevdschee/status/1467418570908909571

**Comment by jeroenheijmans** [comment]
As you know I love this work! But I do think you can compare them *to a degree*. Also, there's a difference between creating a consistent y-axis maximum across years (leaving it up to the viewer whether to compare years), and putting data from various years as series into 1 graph (suggesting as the author that they're comparable).

If you couldn't compare them because of number of players, then we couldn't compare day 20 of a year to day 2 either (people drop off during December). Yet the year-graphs still do so by putting both days in the same graph against the same y-axis (and rightfully so).

But, I also appreciate the idea that it's not possible and respect the choice to leave the website as is.

For that reason I have requested #6 if that's an option it would be properly possible for others to do such a remix if they're curious.

Regardless of whether you'd consider that and/or change anything here: thx for a great visual and updating the data again this year! And: happy puzzling 😄

**Comment by mevdschee** [comment]
@jeroenheijmans You make some very valid points. I've added a link to sync the Y-axis in the bottom of the file, see:

http://www.maurits.vdschee.nl/scatterplot

![image](https://user-images.githubusercontent.com/1288217/145694387-58d14695-3f96-470d-b177-e4552b889765.png)

>Regardless of whether you'd consider that and/or change anything here: thx for a great visual and updating the data again this year! And: happy puzzling 

Thank you for your kind words and for your [infi puzzle](https://aoc.infi.nl/), I had fun again!
